version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80" # Serve the client app on port 3000

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000" # Expose server on port 5000

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
